import 'package:flutter/material.dart';import 'package:flutter_svg_provider/flutter_svg_provider.dart' as fs;import 'package:kuddle_s_application27/core/app_export.dart';import 'package:kuddle_s_application27/widgets/app_bar/appbar_leading_image.dart';import 'package:kuddle_s_application27/widgets/app_bar/appbar_title.dart';import 'package:kuddle_s_application27/widgets/app_bar/custom_app_bar.dart';import 'package:kuddle_s_application27/widgets/custom_elevated_button.dart';import 'package:qr_flutter/qr_flutter.dart';class ViewBookingScreen extends StatelessWidget {const ViewBookingScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: mediaQueryData.size.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 33.v), child: Padding(padding: EdgeInsets.only(left: 15.h, right: 15.h, bottom: 5.v), child: Column(children: [Container(padding: EdgeInsets.symmetric(horizontal: 19.h, vertical: 22.v), decoration: BoxDecoration(image: DecorationImage(image: fs.Svg(ImageConstant.imgGroup72), fit: BoxFit.cover)), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Align(alignment: Alignment.center, child: Text("Hotel Royal", style: theme.textTheme.titleLarge)), SizedBox(height: 3.v), Align(alignment: Alignment.center, child: Container(margin: EdgeInsets.symmetric(horizontal: 52.h), padding: EdgeInsets.all(16.h), decoration: AppDecoration.fillOnPrimary, child: QrImageView(data: 'https://www.google.com', size: 227.v))), SizedBox(height: 55.v), Padding(padding: EdgeInsets.only(right: 22.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Name", style: CustomTextStyles.labelLargeGray400), SizedBox(height: 8.v), Text("Brooklyn Simmons", style: theme.textTheme.titleMedium)]), Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Phone Number", style: CustomTextStyles.labelLargeGray400), SizedBox(height: 6.v), Text("+1 123 1234 456", style: theme.textTheme.titleMedium)])])), SizedBox(height: 28.v), Padding(padding: EdgeInsets.only(right: 42.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Check in Time", style: CustomTextStyles.labelLargeGray400), SizedBox(height: 8.v), Text("June 14, 2023", style: theme.textTheme.titleMedium)]), Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Check out Time", style: CustomTextStyles.labelLargeGray400), SizedBox(height: 8.v), Text("June 18, 2023", style: theme.textTheme.titleMedium)])])), SizedBox(height: 28.v), Padding(padding: EdgeInsets.only(right: 63.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(bottom: 1.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Guest", style: CustomTextStyles.labelLargeGray400), SizedBox(height: 6.v), Text("5", style: theme.textTheme.titleMedium)])), Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Hotel Name", style: CustomTextStyles.labelLargeGray400), SizedBox(height: 8.v), Text("Hotel Royal", style: theme.textTheme.titleMedium)])])), SizedBox(height: 18.v)])), SizedBox(height: 51.v), CustomElevatedButton(height: 49.v, width: 271.h, text: "Download Booking Ticket", buttonStyle: CustomButtonStyles.fillPrimaryTL24)])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 46.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftPrimary, margin: EdgeInsets.only(left: 15.h, top: 12.v, bottom: 12.v), onTap: () {onTapArrowLeft(context);}), title: AppbarTitle(text: "Booking", margin: EdgeInsets.only(left: 14.h))); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
