import '../other_service_screen/widgets/otherservice_item_widget.dart';import 'package:flutter/material.dart';import 'package:kuddle_s_application27/core/app_export.dart';import 'package:kuddle_s_application27/presentation/car_page/car_page.dart';import 'package:kuddle_s_application27/presentation/favorite_page/favorite_page.dart';import 'package:kuddle_s_application27/presentation/last_book_tab_container_page/last_book_tab_container_page.dart';import 'package:kuddle_s_application27/presentation/profile_one_page/profile_one_page.dart';import 'package:kuddle_s_application27/widgets/app_bar/appbar_leading_image.dart';import 'package:kuddle_s_application27/widgets/app_bar/appbar_subtitle.dart';import 'package:kuddle_s_application27/widgets/app_bar/appbar_trailing_circleimage.dart';import 'package:kuddle_s_application27/widgets/app_bar/custom_app_bar.dart';import 'package:kuddle_s_application27/widgets/custom_bottom_app_bar.dart';import 'package:kuddle_s_application27/widgets/custom_search_view.dart';
// ignore_for_file: must_be_immutable
class OtherServiceScreen extends StatelessWidget {OtherServiceScreen({Key? key}) : super(key: key);

TextEditingController searchController = TextEditingController();

GlobalKey<NavigatorState> navigatorKey = GlobalKey();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: SizedBox(width: double.maxFinite, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 18.v), Container(width: 297.h, margin: EdgeInsets.only(left: 15.h), child: Text("Need a professional service?", maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.headlineLarge!.copyWith(height: 1.40))), SizedBox(height: 26.v), Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 15.h), child: CustomSearchView(controller: searchController, hintText: "Search Your Place", alignment: Alignment.center))), SizedBox(height: 25.v), _buildHotel(context), SizedBox(height: 40.v), _buildOtherServices(context), SizedBox(height: 29.v), _buildOtherService(context)])), bottomNavigationBar: _buildHome(context), floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked)); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgMenu, margin: EdgeInsets.only(left: 15.h, top: 19.v, bottom: 18.v)), actions: [AppbarSubtitle(text: "1500.00", margin: EdgeInsets.fromLTRB(15.h, 16.v, 1.h, 15.v)), AppbarTrailingCircleimage(imagePath: ImageConstant.imgEllipse3, margin: EdgeInsets.only(left: 10.h, top: 1.v, right: 16.h))]); } 
/// Section Widget
Widget _buildHotel(BuildContext context) { return SingleChildScrollView(scrollDirection: Axis.horizontal, padding: EdgeInsets.only(right: 15.h), child: IntrinsicWidth(child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(width: 74.h, padding: EdgeInsets.symmetric(horizontal: 19.h, vertical: 10.v), decoration: AppDecoration.fillOnPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Text("Hotel", style: theme.textTheme.titleSmall)), Spacer(), Container(width: 26.h, padding: EdgeInsets.symmetric(vertical: 8.v), decoration: AppDecoration.fillOnPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder13), child: Text("Apartment", style: theme.textTheme.titleSmall)), Container(width: 62.h, margin: EdgeInsets.only(left: 6.h), padding: EdgeInsets.symmetric(horizontal: 19.h, vertical: 9.v), decoration: AppDecoration.fillOnPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Text("Car", style: theme.textTheme.titleSmall)), Container(width: 83.h, margin: EdgeInsets.only(left: 6.h), padding: EdgeInsets.symmetric(horizontal: 19.h, vertical: 8.v), decoration: AppDecoration.fillOnPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Text("Flights", style: theme.textTheme.titleSmall)), Container(width: 86.h, margin: EdgeInsets.only(left: 6.h), padding: EdgeInsets.symmetric(horizontal: 19.h, vertical: 9.v), decoration: AppDecoration.fillOnPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Text("Islands", style: theme.textTheme.titleSmall)), Container(width: 132.h, margin: EdgeInsets.only(left: 6.h), padding: EdgeInsets.symmetric(horizontal: 19.h, vertical: 9.v), decoration: AppDecoration.fillPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Text("Other Service", style: CustomTextStyles.titleSmallOnPrimary))]))); } 
/// Section Widget
Widget _buildOtherServices(BuildContext context) { return Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 15.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("Other Services", style: CustomTextStyles.titleLarge23), Padding(padding: EdgeInsets.only(top: 11.v), child: Text("View All", style: CustomTextStyles.bodyMediumRegular_1))]))); } 
/// Section Widget
Widget _buildOtherService(BuildContext context) { return Expanded(child: Padding(padding: EdgeInsets.only(left: 15.h), child: GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 220.v, crossAxisCount: 3, mainAxisSpacing: 18.h, crossAxisSpacing: 18.h), physics: BouncingScrollPhysics(), itemCount: 9, itemBuilder: (context, index) {return OtherserviceItemWidget(onTapImgHour: () {onTapImgHour(context);});}))); } 
/// Section Widget
Widget _buildHome(BuildContext context) { return CustomBottomAppBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Home: return AppRoutes.carPage; case BottomBarEnum.Vuesaxlinearheart: return AppRoutes.favoritePage; case BottomBarEnum.Bag: return AppRoutes.lastBookTabContainerPage; case BottomBarEnum.User: return AppRoutes.profileOnePage; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.carPage: return CarPage(); case AppRoutes.favoritePage: return FavoritePage(); case AppRoutes.lastBookTabContainerPage: return LastBookTabContainerPage(); case AppRoutes.profileOnePage: return ProfileOnePage(); default: return DefaultWidget();} } 
/// Navigates to the hotelSixScreen when the action is triggered.
onTapImgHour(BuildContext context) { Navigator.pushNamed(context, AppRoutes.hotelSixScreen); } 
 }
